version: '3.8'

services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '${PORT:-3000}:3000'
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules:
